<a href="https://colab.research.google.com/github/gumdropsteve/intro_to_machine_learning/blob/main/day_03/01_hyper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('https://github.com/gumdropsteve/datasets/raw/master/iris.csv')

df

sepal_length  sepal_width  petal_length  petal_width    species  target
0             5.1          3.5           1.4          0.2     setosa       0
1             4.9          3.0           1.4          0.2     setosa       0
2             4.7          3.2           1.3          0.2     setosa       0
3             4.6          3.1           1.5          0.2     setosa       0
4             5.0          3.6           1.4          0.2     setosa       0
..            ...          ...           ...          ...        ...     ...
145           6.7          3.0           5.2          2.3  virginica       2
146           6.3          2.5           5.0          1.9  virginica       2
147           6.5          3.0           5.2          2.0  virginica       2
148           6.2          3.4           5.4          2.3  virginica       2
149           5.9          3.0           5.1          1.8  virginica       2

[150 rows x 6 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)

knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'target'],
      dtype='object')

In [ ]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df.target.astype('int')

knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
knn.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
sum(knn.predict(X) == y) / 150

1.0

In [ ]:
from sklearn.model_selection import train_test_split

# variables that help us predict the target (y)
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
# y is whatever you want to predict ('target', 'labels', etc...)
y = df.target.astype('int')

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

In [ ]:
X_train

sepal_length  sepal_width  petal_length  petal_width
106           4.9          2.5           4.5          1.7
33            5.5          4.2           1.4          0.2
12            4.8          3.0           1.4          0.1
127           6.1          3.0           4.9          1.8
60            5.0          2.0           3.5          1.0
..            ...          ...           ...          ...
75            6.6          3.0           4.4          1.4
143           6.8          3.2           5.9          2.3
9             4.9          3.1           1.5          0.1
5             5.4          3.9           1.7          0.4
27            5.2          3.5           1.5          0.2

[105 rows x 4 columns]

In [ ]:
len(y_test)

45

Random state...

```
random_state : int, RandomState instance or None, optional (default=None)
    If int, random_state is the seed used by the random number generator;
    If RandomState instance, random_state is the random number generator;
    If None, the random number generator is the RandomState instance used
    by np.random.
```

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=2)
X_train.tail(1)

sepal_length  sepal_width  petal_length  petal_width
15           5.7          4.4           1.5          0.4

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=2)
X_train.tail(1)

sepal_length  sepal_width  petal_length  petal_width
15           5.7          4.4           1.5          0.4

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=57)
X_train.tail(1)

sepal_length  sepal_width  petal_length  petal_width
5           5.4          3.9           1.7          0.4

In [ ]:
model = KNeighborsClassifier(n_neighbors=1)

model.fit(X_train, y_train)

preds = model.predict(X_test)

sum(preds == y_test) / 150

0.2866666666666667

Cross-validation,sometimes called out-of-sample testing, is any of various similar model validation techniques for assessing how the results of a statistical analysis will generalize to an independent data set.

More or less... a way to tell if your model is good by testing it with data it wasn't trained on.

In [ ]:
from sklearn.model_selection import cross_val_score

model = KNeighborsClassifier(n_neighbors=3)

X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df.target.astype('int')

cross_val_score(model, X, y)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [ ]:
df.species.value_counts()

versicolor    50
virginica     50
setosa        50
Name: species, dtype: int64

```
scoring

str or callable, default=None
A str (see model evaluation documentation) or a scorer callable object / function with signature scorer(estimator, X, y) which should return only a single value.

Similar to cross_validate but only a single metric is permitted.

If None, the estimator’s default scorer (if available) is used.
```

In [ ]:
cross_val_score(model, X, y, scoring='accuracy')

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [ ]:
cross_val_score(model, X, y, scoring='f1_weighted')

array([0.96658312, 0.96658312, 0.93265993, 0.96658312, 1.        ])

## Switching to a Regression Model

In [ ]:
df = pd.read_parquet('https://github.com/gumdropsteve/datasets/raw/master/nyc_taxi/yellow_tripdata_2019-12.parquet')

df.tail(3)

VendorID tpep_pickup_datetime  ... total_amount  congestion_surcharge
482739       1.0  2019-12-07 19:58:00  ...        18.95                   2.5
482740       2.0  2019-12-14 12:27:36  ...        26.16                   2.5
482741       1.0  2019-12-24 22:50:46  ...         9.80                   2.5

[3 rows x 18 columns]

In [ ]:
df = df.dropna()

X = df[['passenger_count', 'trip_distance', 'RatecodeID', 'PULocationID', 'DOLocationID']]
y = df.fare_amount

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

len(X_train) + len(y_test)

479098

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# use training data to fit the model (fit means train)
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.predict(X_test)

array([11.29049706, 10.23024179, 30.4472895 , ...,  9.76386953,
       14.02758864,  9.59618849])

In [ ]:
preds = model.predict(X_test)

sum(preds == y_test)

0

In [ ]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true=y_test, y_pred=preds)

42.329569242472736

In [ ]:
np.mean(y_test)

13.356901412370359

In [ ]:
preds[-5:]

array([ 8.32046088, 10.64870873,  9.76386953, 14.02758864,  9.59618849])

In [ ]:
y_test[-5:]

313093     9.0
405931    13.0
446443     7.5
333788    15.5
299377     4.5
Name: fare_amount, dtype: float64

In [ ]:
cross_val_score(model, X, y, scoring='r2')

array([1.78217919e-05, 7.26951810e-01, 7.19942712e-01, 7.33881447e-01,
       7.11527498e-01])

## Grid Search

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

def PolynomialRegression(degree=2, **kwargs):
    return make_pipeline(PolynomialFeatures(degree),
                         LinearRegression(**kwargs))

In [ ]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
import numpy as np

def make_data(N, err=1.0, rseed=1):
    # randomly sample the data
    rng = np.random.RandomState(rseed)
    X = rng.rand(N, 1) ** 2
    y = 10 - 1. / (X.ravel() + 0.1)
    if err > 0:
        y += err * rng.randn(N)
    return X, y

X, y = make_data(40)

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'polynomialfeatures__degree': np.arange(21),
              'linearregression__fit_intercept': [True, False],
              'linearregression__normalize': [True, False]}

grid = GridSearchCV(PolynomialRegression(), param_grid, cv=7)

In [ ]:
grid

GridSearchCV(cv=7, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('polynomialfeatures',
                                        PolynomialFeatures(degree=2,
                                                           include_bias=True,
                                                           interaction_only=False,
                                                           order='C')),
                                       ('linearregression',
                                        LinearRegression(copy_X=True,
                                                         fit_intercept=True,
                                                         n_jobs=None,
                                                         normalize=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'linearregression__fit_intercept': [True, False],
                         'linearre

In [ ]:
grid.fit(X, y)

GridSearchCV(cv=7, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('polynomialfeatures',
                                        PolynomialFeatures(degree=2,
                                                           include_bias=True,
                                                           interaction_only=False,
                                                           order='C')),
                                       ('linearregression',
                                        LinearRegression(copy_X=True,
                                                         fit_intercept=True,
                                                         n_jobs=None,
                                                         normalize=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'linearregression__fit_intercept': [True, False],
                         'linearre

In [ ]:
grid.best_params_

{'linearregression__fit_intercept': False,
 'linearregression__normalize': True,
 'polynomialfeatures__degree': 4}

In [ ]:
def PolynomialRegression():
    return make_pipeline(PolynomialFeatures(degree=4),
                         LinearRegression(normalize=True, fit_intercept=False))

In [ ]:
PolynomialRegression()

Pipeline(memory=None,
         steps=[('polynomialfeatures',
                 PolynomialFeatures(degree=4, include_bias=True,
                                    interaction_only=False, order='C')),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None,
                                  normalize=True))],
         verbose=False)

### Simple on Taxi

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

def LR(**kwargs):
    return make_pipeline(LinearRegression(**kwargs))

In [ ]:
param_grid = {'linearregression__fit_intercept': [True, False],
              'linearregression__normalize': [True, False]}

grid = GridSearchCV(LR(), param_grid, cv=7)

In [ ]:
df = pd.read_parquet('https://github.com/gumdropsteve/datasets/raw/master/nyc_taxi/yellow_tripdata_2019-12.parquet')

df = df.dropna()

X = df[['passenger_count', 'trip_distance', 'RatecodeID', 'PULocationID', 'DOLocationID']]
y = df.fare_amount

In [ ]:
grid.fit(X, y)

GridSearchCV(cv=7, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('linearregression',
                                        LinearRegression(copy_X=True,
                                                         fit_intercept=True,
                                                         n_jobs=None,
                                                         normalize=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'linearregression__fit_intercept': [True, False],
                         'linearregression__normalize': [True, False]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
grid.best_params_

{'linearregression__fit_intercept': True, 'linearregression__normalize': False}

In [ ]:
model = LinearRegression()

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

model.fit(X_train, y_train)

preds = model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_true=y_test, y_pred=preds)

0.70873846906502